name = "VMLinuxBindings"
uuid = "3d5d7239-16b4-4651-96ed-9e800c796499"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>"]
version = "0.1.1"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"

[compat]
CBinding = "1"
julia = "1"
